# Generated by Django 4.0.10 on 2023-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('unit_type', models.CharField(choices=[('Hotel', 'hotel'), ('Apartment', 'apartment'), ('House', 'house'), ('Room', 'room'), ('Trailer', 'trailer'), ('Igloo', 'igloo')], default='hotel', max_length=30)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='inactive', max_length=20)),
            ],
        ),
    ]
