# Generated by Django 4.0.10 on 2023-06-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rentalunit_amenitieslist_availability_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rulebook',
            fields=[
                ('rental_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.rentalunit')),
                ('cancellation_policy', models.CharField(blank=True, choices=[('Flexible', 'flexible'), ('Moderate', 'moderate'), ('Firm', 'firm'), ('Strict', 'strict'), ('Long Term', 'long Term'), ('Non-refundable', 'non-refundable')], max_length=50)),
                ('house_rules', models.TextField(blank=True)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('events_allowed', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('commercial_photo_film_allowed', models.BooleanField(default=False)),
                ('guest_requirements', models.TextField(blank=True)),
                ('laws_and_regulations', models.TextField(blank=True)),
            ],
        ),
    ]
