# Generated by Django 4.0.10 on 2023-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rentalunit_detailedlocation_amenitieslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
    ]
