# Generated by Django 4.0.10 on 2023-05-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rentalunit_amenitieslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenitieslist',
            name='id',
        ),
        migrations.AlterField(
            model_name='amenitieslist',
            name='rental_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.rentalunit'),
        ),
    ]
