# Generated by Django 4.0.10 on 2023-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rentalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='house_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalunit',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalunit',
            name='wifi_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rentalunit',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
