# Generated by Django 4.0.10 on 2023-05-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_amenitieslist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedLocation',
            fields=[
                ('rental_unit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.rentalunit')),
                ('neighborhood_description', models.TextField(default='Describe the neighborhood of your place.')),
                ('getting_around', models.TextField(default='Any tips about how to reach your place or interesting things around.')),
                ('location_sharing', models.BooleanField(default=False)),
                ('address1', models.CharField(blank=True, max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(blank=True, max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(blank=True, max_length=1024, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=3, verbose_name='Country')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
    ]
