# Generated by Django 4.0.10 on 2023-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rentalunit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
