# Generated by Django 4.0.10 on 2023-05-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_amenitieslist_rental_unit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmenitiesList',
            new_name='Amenities',
        ),
    ]
