# Generated by Django 4.0.10 on 2023-06-05 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_guidebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidebook',
            name='check_in_end_time',
            field=models.TimeField(default=datetime.time(18, 0), null=True),
        ),
        migrations.AlterField(
            model_name='guidebook',
            name='check_in_start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='guidebook',
            name='check_out_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
