# Generated by Django 4.0.10 on 2023-05-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_rental_unit_id_detailedlocation_rental_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailedLocation',
            new_name='Location',
        ),
    ]
