# Generated by Django 4.0.10 on 2023-05-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_detailedlocation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOrSpace',
            fields=[
                ('rental_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.rentalunit')),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('room_type', models.CharField(blank=True, choices=[], max_length=20)),
                ('bed_type', models.CharField(blank=True, choices=[], max_length=20)),
                ('bathroom_type', models.CharField(blank=True, choices=[], max_length=20)),
                ('tv', models.BooleanField(default=False)),
                ('shower_type', models.CharField(blank=True, choices=[], max_length=20)),
                ('accessible', models.BooleanField(default=False)),
            ],
        ),
    ]
