# Generated by Django 4.0.10 on 2023-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_guidebook_check_in_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'restaurant'), ('Night Club', 'night club'), ('Beach', 'beach')], max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=1024, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=3, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='place',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='ZIP / Postal code'),
        ),
    ]
