# Generated by Django 4.0.10 on 2023-05-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_roomorspace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomOrSpace',
            new_name='Area',
        ),
    ]
