# Generated by Django 4.0.10 on 2023-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_guidebook_places_remove_place_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='shower_type',
        ),
        migrations.AddField(
            model_name='guidebook',
            name='check_out_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guidebook',
            name='check_in_method',
            field=models.CharField(choices=[('Smart lock', 'smart lock'), ('Keypad', 'keypad'), ('Lockbox', 'lockbox'), ('Building Staff', 'Building staff'), ('Host greets you', 'host greets you')], default='Host greets you', max_length=255),
        ),
        migrations.AlterField(
            model_name='guidebook',
            name='house_manual',
            field=models.TextField(blank=True, default='Tell your guests about how things work at your place.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='getting_around',
            field=models.TextField(default='Any tips about how to reach your place.'),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rentalunit',
            name='unit_type',
            field=models.CharField(choices=[('Hotel', 'hotel'), ('Apartment', 'apartment'), ('House', 'house'), ('Room', 'room'), ('Trailer', 'trailer'), ('Igloo', 'igloo'), ('Villa', 'villa')], default='hotel', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('King', 'king'), ('Queen', 'queen'), ('Full', 'Full'), ('Twin', 'twin'), ('Single', 'single'), ('Crib', 'crib')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Bedroom', 'bedroom'), ('Living room', 'living room'), ('Game room', 'game room'), ('Family room', 'family room'), ('Studio', 'studio'), ('Office', 'office'), ('Bathroom (full)', 'bathroom (full)'), ('Bathroom (half)', 'bathroom (half)'), ('Loft', 'loft'), ('Basement', 'basement')], max_length=20),
        ),
    ]
