# Generated by Django 4.0.10 on 2023-05-30 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_room_delete_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('rental_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.rentalunit')),
                ('night_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('smart_pricing', models.BooleanField(default=False)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('YEN', 'YEN')], default='USD', max_length=30)),
                ('week_discount', models.IntegerField(default=0)),
                ('month_discount', models.IntegerField(default=0)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
