# Generated by Django 4.0.10 on 2023-05-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pet', 'pet'), ('Transport', 'transport'), ('Extra guest', 'extra guest')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('rental_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rentalunit')),
            ],
            options={
                'unique_together': {('rental_unit', 'name')},
            },
        ),
    ]
