# Generated by Django 4.0.10 on 2023-06-09 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_calendarevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
