# Generated by Django 4.0.10 on 2023-06-01 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_fee_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('rental_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.rentalunit')),
                ('min_stay', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('max_stay', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(90)])),
                ('min_notice', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('max_notice', models.IntegerField(default=365, validators=[django.core.validators.MinValueValidator(31), django.core.validators.MaxValueValidator(365)])),
                ('prep_time', models.IntegerField(default=72, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)])),
            ],
        ),
    ]
