# Generated by Django 4.0.10 on 2023-06-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('rental_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.rentalunit')),
                ('entrance', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('lavatory_equipment', models.BooleanField(default=False)),
                ('door_width', models.BooleanField(default=False)),
                ('stairs', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='reason',
            field=models.CharField(choices=[('Reservation', 'reservation'), ('Blocked', 'blocked')], max_length=50),
        ),
    ]
