# Generated by Django 4.0.10 on 2023-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_availability_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalunit',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
