# Generated by Django 4.0.10 on 2023-06-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_rentalunit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='night_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
