# Generated by Django 4.0.10 on 2023-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_calendarevent_night_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='night_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
