# Generated by Django 4.0.10 on 2023-06-14 14:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_reservationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('night_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('rental_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rentalunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
