# Generated by Django 4.0.10 on 2023-06-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='night_price',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='night_subtotal',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='notes',
        ),
    ]
