# Generated by Django 4.0.10 on 2023-06-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cancellationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
