# Generated by Django 4.0.10 on 2023-06-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cancellationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='rental_unit',
        ),
    ]
