# Generated by Django 4.0.10 on 2023-06-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reservation_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='days',
            new_name='nights',
        ),
    ]
