# Generated by Django 4.0.10 on 2023-06-17 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_rulebook_cancellation_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrequest',
            name='refund',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
