# Generated by Django 4.0.10 on 2023-06-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_changerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='nights_diff',
        ),
    ]
