# Generated by Django 4.0.10 on 2023-06-20 19:03

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_rentalunit_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(null=True, upload_to=core.models.rental_unit_image_file_path)),
                ('rental_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentalunit')),
            ],
        ),
    ]
