# Generated by Django 4.0.10 on 2023-06-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalunit',
            old_name='images',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
