# Generated by Django 4.0.10 on 2023-05-17 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rentalunit_house_rules_rentalunit_max_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
